/*-----------------------------------------------------------------------------+    
Copyright (c) 1999-2006: Cortex Software GmbH, Kantstrasse 57, Berlin
+------------------------------------------------------------------------------+
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
+-----------------------------------------------------------------------------*/
#ifndef __StatVarDescT_JOFA_040614_H__
#define __StatVarDescT_JOFA_040614_H__

#include <boost/itl_xt/enum_bitset.hpp>
namespace boost{namespace itl
{

    /// Skalenniveau der Skala
    enum KindOfScaleET { nominal_scale, ordinal_scale, interval_scale, ratio_scale };

    //JODO Noch nicht ganz klar ob wirs so brauchen
    // Konzept: Zähltupeln sind immer interger-codier
    /// Werte der Skala
    enum VarValueET 
    {
        integer_value, 
        interval_value, 
        string_value, 
        class_value,
        VarValueET_size 
    };

    /// Flags für eine Variable
    enum StatVarPropertyET
    {
        dependent,                // Abhängige Variable
        // independent,            // Unabhängige Variable ?? JODO Können beide gleichzeitig false sein? (nur restricting)
        restricting,            // Restriktionsvariable
        StatVarPropertyET_size
    };

    typedef enum_bitset<StatVarPropertyET, StatVarPropertyET_size> StatVarPropertySetTD ; 


    /*  class StatVarDescT: Beschreibung der Eigenschaften von Variablen einer Statistik 
        (auch bekannt als Stochastische Variable). 

        Zuständigkeit: Beschreibt wichtige Eigenschaften von Datenbank-Feldern im Kontext
        von Statistischen Auswertungen.

        Zusammenarbeit:  
    */
    class StatVarDescT
    {
    public:
        bool isDependent()const;
        
    private:
    };


}} // namespace itl boost

#endif // __StatVarDescT_JOFA_040614_H__

