Document: tspikes
Title: Debian tspikes Manual
Author: <insert document author here>
Abstract: This manual describes what tspikes is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tspikes/tspikes.sgml.gz

Format: postscript
Files: /usr/share/doc/tspikes/tspikes.ps.gz

Format: text
Files: /usr/share/doc/tspikes/tspikes.text.gz

Format: HTML
Index: /usr/share/doc/tspikes/html/index.html
Files: /usr/share/doc/tspikes/html/*.html

  
